In [1]:
print("Dividend Puzzle Analyzer")
print("Day 2 - Data Analysis Setup")

Dividend Puzzle Analyzer
Day 2 - Data Analysis Setup

In [2]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.5

In [3]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.6

In [4]:
import matplotlib.pyplot as plt

print("Matplotlib is working!")

Matplotlib is building the font cache; this may take a moment.

Matplotlib is working!

In [5]:
import seaborn as sns

print("Seaborn is working!")

Seaborn is working!

In [6]:
import pandas as pd

companies = pd.read_csv("../datasets/raw/companies.csv")

companies

             company ticker  start_year  end_year
0              Apple   AAPL        2015      2025
1          Microsoft   MSFT        2015      2025
2          Coca-Cola     KO        2015      2025
3            PepsiCo    PEP        2015      2025
4  Johnson & Johnson    JNJ        2015      2025
5   Procter & Gamble     PG        2015      2025
6         McDonald's    MCD        2015      2025
7            Walmart    WMT        2015      2025
8        Exxon Mobil    XOM        2015      2025
9            Verizon     VZ        2015      2025

In [7]:
print("Number of companies:", len(companies))

Number of companies: 10

In [8]:
print(companies.columns.tolist())

['company', 'ticker', 'start_year', 'end_year']

In [9]:
companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   company     10 non-null     str
 1   ticker      10 non-null     str
 2   start_year  10 non-null     int64
 3   end_year    10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes

In [10]:
import yfinance as yf

apple = yf.Ticker("AAPL")

print("Company:", apple.info.get("longName"))

Company: Apple Inc.

In [11]:
apple_prices = apple.history(
    start="2015-01-01",
    end="2026-01-01"
)

apple_prices.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2015-01-02 00:00:00-05:00,24.627201,24.638257,23.733998,24.171757,212818400,0.0,0.0
2015-01-05 00:00:00-05:00,23.941819,24.021411,23.305080,23.490795,257142000,0.0,0.0
2015-01-06 00:00:00-05:00,23.554918,23.751688,23.132636,23.493013,263188400,0.0,0.0
2015-01-07 00:00:00-05:00,23.700833,23.921923,23.590288,23.822433,160423600,0.0,0.0
2015-01-08 00:00:00-05:00,24.149651,24.795233,24.032472,24.737749,237458000,0.0,0.0

In [12]:
print("Rows:", len(apple_prices))
print("Columns:", len(apple_prices.columns))

Rows: 2766
Columns: 7

In [13]:
print("First date:", apple_prices.index.min())
print("Last date:", apple_prices.index.max())

First date: 2015-01-02 00:00:00-05:00
Last date: 2025-12-31 00:00:00-05:00

In [14]:
apple_dividends = apple.dividends

apple_dividends.head(10)

Date
1987-05-11 09:30:00-04:00    0.000536
1987-08-10 09:30:00-04:00    0.000536
1987-11-17 09:30:00-05:00    0.000714
1988-02-12 09:30:00-05:00    0.000714
1988-05-16 09:30:00-04:00    0.000714
1988-08-15 09:30:00-04:00    0.000714
1988-11-21 09:30:00-05:00    0.000893
1989-02-17 09:30:00-05:00    0.000893
1989-05-22 09:30:00-04:00    0.000893
1989-08-21 09:30:00-04:00    0.000893
Name: Dividends, dtype: float64

In [15]:
annual_dividends = apple_dividends.resample("YE").sum()

annual_dividends

Date
1987-12-31 00:00:00-05:00    0.001786
1988-12-31 00:00:00-05:00    0.003035
1989-12-31 00:00:00-05:00    0.003661
1990-12-31 00:00:00-05:00    0.004017
1991-12-31 00:00:00-05:00    0.004284
1992-12-31 00:00:00-05:00    0.004284
1993-12-31 00:00:00-05:00    0.004284
1994-12-31 00:00:00-05:00    0.004284
1995-12-31 00:00:00-05:00    0.004284
1996-12-31 00:00:00-05:00    0.000000
1997-12-31 00:00:00-05:00    0.000000
1998-12-31 00:00:00-05:00    0.000000
1999-12-31 00:00:00-05:00    0.000000
2000-12-31 00:00:00-05:00    0.000000
2001-12-31 00:00:00-05:00    0.000000
2002-12-31 00:00:00-05:00    0.000000
2003-12-31 00:00:00-05:00    0.000000
2004-12-31 00:00:00-05:00    0.000000
2005-12-31 00:00:00-05:00    0.000000
2006-12-31 00:00:00-05:00    0.000000
2007-12-31 00:00:00-05:00    0.000000
2008-12-31 00:00:00-05:00    0.000000
2009-12-31 00:00:00-05:00    0.000000
2010-12-31 00:00:00-05:00    0.000000
2011-12-31 00:00:00-05:00    0.000000
2012-12-31 00:00:00-05:00    0.189286
2013-12-31 00:00:00-05:00    0.421430
2014-12-31 00:00:00-05:00    0.461429
2015-12-31 00:00:00-05:00    0.507500
2016-12-31 00:00:00-05:00    0.557500
2017-12-31 00:00:00-05:00    0.615000
2018-12-31 00:00:00-05:00    0.705000
2019-12-31 00:00:00-05:00    0.760000
2020-12-31 00:00:00-05:00    0.807500
2021-12-31 00:00:00-05:00    0.865000
2022-12-31 00:00:00-05:00    0.910000
2023-12-31 00:00:00-05:00    0.950000
2024-12-31 00:00:00-05:00    0.990000
2025-12-31 00:00:00-05:00    1.030000
2026-12-31 00:00:00-05:00    0.800000
Freq: YE-DEC, Name: Dividends, dtype: float64

In [16]:
annual_dividends = annual_dividends.reset_index()

annual_dividends.columns = ["date", "dividend_per_share"]

annual_dividends["year"] = annual_dividends["date"].dt.year

annual_dividends = annual_dividends[
    ["year", "dividend_per_share"]
]

annual_dividends

    year  dividend_per_share
0   1987            0.001786
1   1988            0.003035
2   1989            0.003661
3   1990            0.004017
4   1991            0.004284
5   1992            0.004284
6   1993            0.004284
7   1994            0.004284
8   1995            0.004284
9   1996            0.000000
10  1997            0.000000
11  1998            0.000000
12  1999            0.000000
13  2000            0.000000
14  2001            0.000000
15  2002            0.000000
16  2003            0.000000
17  2004            0.000000
18  2005            0.000000
19  2006            0.000000
20  2007            0.000000
21  2008            0.000000
22  2009            0.000000
23  2010            0.000000
24  2011            0.000000
25  2012            0.189286
26  2013            0.421430
27  2014            0.461429
28  2015            0.507500
29  2016            0.557500
30  2017            0.615000
31  2018            0.705000
32  2019            0.760000
33  2020            0.807500
34  2021            0.865000
35  2022            0.910000
36  2023            0.950000
37  2024            0.990000
38  2025            1.030000
39  2026            0.800000

In [17]:
annual_dividends["company"] = "Apple"
annual_dividends["ticker"] = "AAPL"

annual_dividends

    year  dividend_per_share company ticker
0   1987            0.001786   Apple   AAPL
1   1988            0.003035   Apple   AAPL
2   1989            0.003661   Apple   AAPL
3   1990            0.004017   Apple   AAPL
4   1991            0.004284   Apple   AAPL
5   1992            0.004284   Apple   AAPL
6   1993            0.004284   Apple   AAPL
7   1994            0.004284   Apple   AAPL
8   1995            0.004284   Apple   AAPL
9   1996            0.000000   Apple   AAPL
10  1997            0.000000   Apple   AAPL
11  1998            0.000000   Apple   AAPL
12  1999            0.000000   Apple   AAPL
13  2000            0.000000   Apple   AAPL
14  2001            0.000000   Apple   AAPL
15  2002            0.000000   Apple   AAPL
16  2003            0.000000   Apple   AAPL
17  2004            0.000000   Apple   AAPL
18  2005            0.000000   Apple   AAPL
19  2006            0.000000   Apple   AAPL
20  2007            0.000000   Apple   AAPL
21  2008            0.000000   Apple   AAPL
22  2009            0.000000   Apple   AAPL
23  2010            0.000000   Apple   AAPL
24  2011            0.000000   Apple   AAPL
25  2012            0.189286   Apple   AAPL
26  2013            0.421430   Apple   AAPL
27  2014            0.461429   Apple   AAPL
28  2015            0.507500   Apple   AAPL
29  2016            0.557500   Apple   AAPL
30  2017            0.615000   Apple   AAPL
31  2018            0.705000   Apple   AAPL
32  2019            0.760000   Apple   AAPL
33  2020            0.807500   Apple   AAPL
34  2021            0.865000   Apple   AAPL
35  2022            0.910000   Apple   AAPL
36  2023            0.950000   Apple   AAPL
37  2024            0.990000   Apple   AAPL
38  2025            1.030000   Apple   AAPL
39  2026            0.800000   Apple   AAPL

In [18]:
apple_prices = apple_prices.reset_index()

apple_prices["year"] = apple_prices["Date"].dt.year

year_end_prices = (
    apple_prices
    .sort_values("Date")
    .groupby("year")
    .tail(1)
)

year_end_prices = year_end_prices[
    ["year", "Close"]
]

year_end_prices

      year       Close
251   2015   23.668442
503   2016   26.622358
754   2017   39.524700
1005  2018   37.394249
1257  2019   70.659355
1510  2020  128.816742
1762  2021  173.449448
2013  2022  127.651520
2263  2023  190.211044
2515  2024  248.615784
2765  2025  271.122009

In [19]:
apple_data = pd.merge(
    annual_dividends,
    year_end_prices,
    on="year",
    how="left"
)

apple_data

    year  dividend_per_share company ticker       Close
0   1987            0.001786   Apple   AAPL         NaN
1   1988            0.003035   Apple   AAPL         NaN
2   1989            0.003661   Apple   AAPL         NaN
3   1990            0.004017   Apple   AAPL         NaN
4   1991            0.004284   Apple   AAPL         NaN
5   1992            0.004284   Apple   AAPL         NaN
6   1993            0.004284   Apple   AAPL         NaN
7   1994            0.004284   Apple   AAPL         NaN
8   1995            0.004284   Apple   AAPL         NaN
9   1996            0.000000   Apple   AAPL         NaN
10  1997            0.000000   Apple   AAPL         NaN
11  1998            0.000000   Apple   AAPL         NaN
12  1999            0.000000   Apple   AAPL         NaN
13  2000            0.000000   Apple   AAPL         NaN
14  2001            0.000000   Apple   AAPL         NaN
15  2002            0.000000   Apple   AAPL         NaN
16  2003            0.000000   Apple   AAPL         NaN
17  2004            0.000000   Apple   AAPL         NaN
18  2005            0.000000   Apple   AAPL         NaN
19  2006            0.000000   Apple   AAPL         NaN
20  2007            0.000000   Apple   AAPL         NaN
21  2008            0.000000   Apple   AAPL         NaN
22  2009            0.000000   Apple   AAPL         NaN
23  2010            0.000000   Apple   AAPL         NaN
24  2011            0.000000   Apple   AAPL         NaN
25  2012            0.189286   Apple   AAPL         NaN
26  2013            0.421430   Apple   AAPL         NaN
27  2014            0.461429   Apple   AAPL         NaN
28  2015            0.507500   Apple   AAPL   23.668442
29  2016            0.557500   Apple   AAPL   26.622358
30  2017            0.615000   Apple   AAPL   39.524700
31  2018            0.705000   Apple   AAPL   37.394249
32  2019            0.760000   Apple   AAPL   70.659355
33  2020            0.807500   Apple   AAPL  128.816742
34  2021            0.865000   Apple   AAPL  173.449448
35  2022            0.910000   Apple   AAPL  127.651520
36  2023            0.950000   Apple   AAPL  190.211044
37  2024            0.990000   Apple   AAPL  248.615784
38  2025            1.030000   Apple   AAPL  271.122009
39  2026            0.800000   Apple   AAPL         NaN

In [20]:
apple_data["dividend_yield"] = (
    apple_data["dividend_per_share"]
    / apple_data["Close"]
) * 100

apple_data

    year  dividend_per_share company ticker       Close  dividend_yield
0   1987            0.001786   Apple   AAPL         NaN             NaN
1   1988            0.003035   Apple   AAPL         NaN             NaN
2   1989            0.003661   Apple   AAPL         NaN             NaN
3   1990            0.004017   Apple   AAPL         NaN             NaN
4   1991            0.004284   Apple   AAPL         NaN             NaN
5   1992            0.004284   Apple   AAPL         NaN             NaN
6   1993            0.004284   Apple   AAPL         NaN             NaN
7   1994            0.004284   Apple   AAPL         NaN             NaN
8   1995            0.004284   Apple   AAPL         NaN             NaN
9   1996            0.000000   Apple   AAPL         NaN             NaN
10  1997            0.000000   Apple   AAPL         NaN             NaN
11  1998            0.000000   Apple   AAPL         NaN             NaN
12  1999            0.000000   Apple   AAPL         NaN             NaN
13  2000            0.000000   Apple   AAPL         NaN             NaN
14  2001            0.000000   Apple   AAPL         NaN             NaN
15  2002            0.000000   Apple   AAPL         NaN             NaN
16  2003            0.000000   Apple   AAPL         NaN             NaN
17  2004            0.000000   Apple   AAPL         NaN             NaN
18  2005            0.000000   Apple   AAPL         NaN             NaN
19  2006            0.000000   Apple   AAPL         NaN             NaN
20  2007            0.000000   Apple   AAPL         NaN             NaN
21  2008            0.000000   Apple   AAPL         NaN             NaN
22  2009            0.000000   Apple   AAPL         NaN             NaN
23  2010            0.000000   Apple   AAPL         NaN             NaN
24  2011            0.000000   Apple   AAPL         NaN             NaN
25  2012            0.189286   Apple   AAPL         NaN             NaN
26  2013            0.421430   Apple   AAPL         NaN             NaN
27  2014            0.461429   Apple   AAPL         NaN             NaN
28  2015            0.507500   Apple   AAPL   23.668442        2.144205
29  2016            0.557500   Apple   AAPL   26.622358        2.094104
30  2017            0.615000   Apple   AAPL   39.524700        1.555989
31  2018            0.705000   Apple   AAPL   37.394249        1.885317
32  2019            0.760000   Apple   AAPL   70.659355        1.075583
33  2020            0.807500   Apple   AAPL  128.816742        0.626860
34  2021            0.865000   Apple   AAPL  173.449448        0.498704
35  2022            0.910000   Apple   AAPL  127.651520        0.712878
36  2023            0.950000   Apple   AAPL  190.211044        0.499445
37  2024            0.990000   Apple   AAPL  248.615784        0.398205
38  2025            1.030000   Apple   AAPL  271.122009        0.379903
39  2026            0.800000   Apple   AAPL         NaN             NaN

In [21]:
apple_data = apple_data.rename(
    columns={"Close": "year_end_price"}
)

apple_data

    year  dividend_per_share company ticker  year_end_price  dividend_yield
0   1987            0.001786   Apple   AAPL             NaN             NaN
1   1988            0.003035   Apple   AAPL             NaN             NaN
2   1989            0.003661   Apple   AAPL             NaN             NaN
3   1990            0.004017   Apple   AAPL             NaN             NaN
4   1991            0.004284   Apple   AAPL             NaN             NaN
5   1992            0.004284   Apple   AAPL             NaN             NaN
6   1993            0.004284   Apple   AAPL             NaN             NaN
7   1994            0.004284   Apple   AAPL             NaN             NaN
8   1995            0.004284   Apple   AAPL             NaN             NaN
9   1996            0.000000   Apple   AAPL             NaN             NaN
10  1997            0.000000   Apple   AAPL             NaN             NaN
11  1998            0.000000   Apple   AAPL             NaN             NaN
12  1999            0.000000   Apple   AAPL             NaN             NaN
13  2000            0.000000   Apple   AAPL             NaN             NaN
14  2001            0.000000   Apple   AAPL             NaN             NaN
15  2002            0.000000   Apple   AAPL             NaN             NaN
16  2003            0.000000   Apple   AAPL             NaN             NaN
17  2004            0.000000   Apple   AAPL             NaN             NaN
18  2005            0.000000   Apple   AAPL             NaN             NaN
19  2006            0.000000   Apple   AAPL             NaN             NaN
20  2007            0.000000   Apple   AAPL             NaN             NaN
21  2008            0.000000   Apple   AAPL             NaN             NaN
22  2009            0.000000   Apple   AAPL             NaN             NaN
23  2010            0.000000   Apple   AAPL             NaN             NaN
24  2011            0.000000   Apple   AAPL             NaN             NaN
25  2012            0.189286   Apple   AAPL             NaN             NaN
26  2013            0.421430   Apple   AAPL             NaN             NaN
27  2014            0.461429   Apple   AAPL             NaN             NaN
28  2015            0.507500   Apple   AAPL       23.668442        2.144205
29  2016            0.557500   Apple   AAPL       26.622358        2.094104
30  2017            0.615000   Apple   AAPL       39.524700        1.555989
31  2018            0.705000   Apple   AAPL       37.394249        1.885317
32  2019            0.760000   Apple   AAPL       70.659355        1.075583
33  2020            0.807500   Apple   AAPL      128.816742        0.626860
34  2021            0.865000   Apple   AAPL      173.449448        0.498704
35  2022            0.910000   Apple   AAPL      127.651520        0.712878
36  2023            0.950000   Apple   AAPL      190.211044        0.499445
37  2024            0.990000   Apple   AAPL      248.615784        0.398205
38  2025            1.030000   Apple   AAPL      271.122009        0.379903
39  2026            0.800000   Apple   AAPL             NaN             NaN

In [22]:
apple_data.to_csv(
    "../datasets/raw/AAPL_market_dividend_data.csv",
    index=False
)