In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
companies = pd.read_csv(
    "../datasets/raw/companies.csv"
)

companies

             company ticker  start_year  end_year
0              Apple   AAPL        2015      2025
1          Microsoft   MSFT        2015      2025
2          Coca-Cola     KO        2015      2025
3            PepsiCo    PEP        2015      2025
4  Johnson & Johnson    JNJ        2015      2025
5   Procter & Gamble     PG        2015      2025
6         McDonald's    MCD        2015      2025
7            Walmart    WMT        2015      2025
8        Exxon Mobil    XOM        2015      2025
9            Verizon     VZ        2015      2025

In [3]:
print(companies.columns.tolist())

['company', 'ticker', 'start_year', 'end_year']

In [4]:
ticker = companies["ticker"].iloc[0]

print(ticker)

AAPL

In [5]:
stock = yf.Ticker(ticker)

income_statement = stock.income_stmt

income_statement

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [6]:
revenue = stock.financials.loc["Total Revenue"]

revenue

2025-09-30    4.161610e+11
2024-09-30    3.910350e+11
2023-09-30    3.832850e+11
2022-09-30    3.943280e+11
2021-09-30             NaN
Name: Total Revenue, dtype: float64

In [7]:
net_income = stock.financials.loc["Net Income"]

net_income

2025-09-30    1.120100e+11
2024-09-30    9.373600e+10
2023-09-30    9.699500e+10
2022-09-30    9.980300e+10
2021-09-30             NaN
Name: Net Income, dtype: float64

In [8]:
balance_sheet = stock.balance_sheet

balance_sheet

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Treasury Shares Number,NaN,NaN,0.000000e+00,NaN,NaN
Ordinary Shares Number,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Share Issued,1.477326e+10,1.511679e+10,1.555006e+10,1.594342e+10,NaN
Net Debt,6.272300e+10,7.668600e+10,8.112300e+10,9.642300e+10,NaN
Total Debt,9.865700e+10,1.066290e+11,1.110880e+11,1.324800e+11,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,5.469700e+10,6.517100e+10,6.155500e+10,4.830400e+10,NaN
Other Short Term Investments,1.876300e+10,3.522800e+10,3.159000e+10,2.465800e+10,NaN
Cash And Cash Equivalents,3.593400e+10,2.994300e+10,2.996500e+10,2.364600e+10,NaN
Cash Equivalents,7.667000e+09,2.744000e+09,1.606000e+09,5.100000e+09,NaN
Cash Financial,2.826700e+10,2.719900e+10,2.835900e+10,1.854600e+10,NaN

In [9]:
assets = balance_sheet.loc["Total Assets"]

assets

2025-09-30    3.592410e+11
2024-09-30    3.649800e+11
2023-09-30    3.525830e+11
2022-09-30    3.527550e+11
2021-09-30             NaN
Name: Total Assets, dtype: float64

In [10]:
[row for row in balance_sheet.index if "Debt" in row]

['Net Debt',
 'Total Debt',
 'Long Term Debt And Capital Lease Obligation',
 'Long Term Debt',
 'Current Debt And Capital Lease Obligation',
 'Current Debt']

In [11]:
debt = balance_sheet.loc["Total Debt"]

debt

2025-09-30    9.865700e+10
2024-09-30    1.066290e+11
2023-09-30    1.110880e+11
2022-09-30    1.324800e+11
2021-09-30             NaN
Name: Total Debt, dtype: float64

In [12]:
eps_data = stock.get_earnings_dates()

eps_data.head()

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2026-10-29 16:00:00-04:00          1.98           NaN          NaN
2026-07-30 16:00:00-04:00          1.89          2.02         6.74
2026-04-30 16:00:00-04:00          1.94          2.01         3.46
2026-01-29 16:00:00-05:00          2.67          2.84         6.34
2025-10-30 16:00:00-04:00          1.77          1.85         4.52

In [13]:
test_record = {
    "ticker": ticker,
    "revenue": revenue.iloc[0] if len(revenue) > 0 else np.nan,
    "net_income": net_income.iloc[0] if len(net_income) > 0 else np.nan,
    "total_assets": assets.iloc[0] if len(assets) > 0 else np.nan
}

test_record

{'ticker': 'AAPL',
 'revenue': np.float64(416161000000.0),
 'net_income': np.float64(112010000000.0),
 'total_assets': np.float64(359241000000.0)}

In [14]:
print(revenue.index)

DatetimeIndex(['2025-09-30', '2024-09-30', '2023-09-30', '2022-09-30',
               '2021-09-30'],
              dtype='datetime64[s]', freq=None)

In [15]:
revenue_yearly = revenue.copy()

revenue_yearly.index = pd.to_datetime(
    revenue_yearly.index
).year

revenue_yearly

2025    4.161610e+11
2024    3.910350e+11
2023    3.832850e+11
2022    3.943280e+11
2021             NaN
Name: Total Revenue, dtype: float64

In [16]:
net_income_yearly = net_income.copy()

net_income_yearly.index = pd.to_datetime(
    net_income_yearly.index
).year

net_income_yearly

2025    1.120100e+11
2024    9.373600e+10
2023    9.699500e+10
2022    9.980300e+10
2021             NaN
Name: Net Income, dtype: float64

In [17]:
test_fundamentals = pd.DataFrame({
    "ticker": ticker,
    "year": revenue_yearly.index,
    "revenue": revenue_yearly.values
})

In [18]:
test_fundamentals

  ticker  year       revenue
0   AAPL  2025  4.161610e+11
1   AAPL  2024  3.910350e+11
2   AAPL  2023  3.832850e+11
3   AAPL  2022  3.943280e+11
4   AAPL  2021           NaN

In [19]:
net_income_df = pd.DataFrame({
    "year": net_income_yearly.index,
    "net_income": net_income_yearly.values
})

In [20]:
test_fundamentals = test_fundamentals.merge(
    net_income_df,
    on="year",
    how="left"
)

In [21]:
test_fundamentals

  ticker  year       revenue    net_income
0   AAPL  2025  4.161610e+11  1.120100e+11
1   AAPL  2024  3.910350e+11  9.373600e+10
2   AAPL  2023  3.832850e+11  9.699500e+10
3   AAPL  2022  3.943280e+11  9.980300e+10
4   AAPL  2021           NaN           NaN

In [22]:
assets_yearly = assets.copy()

assets_yearly.index = pd.to_datetime(
    assets_yearly.index
).year

assets_df = pd.DataFrame({
    "year": assets_yearly.index,
    "total_assets": assets_yearly.values
})

In [24]:
test_fundamentals = test_fundamentals.merge(
    assets_df,
    on="year",
    how="left"
)

In [25]:
test_fundamentals

  ticker  year       revenue    net_income  total_assets
0   AAPL  2025  4.161610e+11  1.120100e+11  3.592410e+11
1   AAPL  2024  3.910350e+11  9.373600e+10  3.649800e+11
2   AAPL  2023  3.832850e+11  9.699500e+10  3.525830e+11
3   AAPL  2022  3.943280e+11  9.980300e+10  3.527550e+11
4   AAPL  2021           NaN           NaN           NaN

In [26]:
def get_fundamentals(ticker):
    try:
        stock = yf.Ticker(ticker)

        financials = stock.financials
        balance_sheet = stock.balance_sheet

        if financials.empty:
            return pd.DataFrame()

        # Revenue
        if "Total Revenue" in financials.index:
            revenue = financials.loc["Total Revenue"].copy()
        else:
            revenue = pd.Series(dtype=float)

        # Net Income
        if "Net Income" in financials.index:
            net_income = financials.loc["Net Income"].copy()
        else:
            net_income = pd.Series(dtype=float)

        # Assets
        if "Total Assets" in balance_sheet.index:
            total_assets = balance_sheet.loc["Total Assets"].copy()
        else:
            total_assets = pd.Series(dtype=float)

        # Convert dates to years
        revenue.index = pd.to_datetime(
            revenue.index
        ).year

        net_income.index = pd.to_datetime(
            net_income.index
        ).year

        total_assets.index = pd.to_datetime(
            total_assets.index
        ).year

        result = pd.DataFrame({
            "year": revenue.index,
            "revenue": revenue.values
        })

        result["net_income"] = (
            result["year"]
            .map(net_income)
        )

        result["total_assets"] = (
            result["year"]
            .map(total_assets)
        )

        result["ticker"] = ticker

        return result[
            [
                "ticker",
                "year",
                "revenue",
                "net_income",
                "total_assets"
            ]
        ]

    except Exception as e:
        print(f"Error for {ticker}: {e}")
        return pd.DataFrame()

In [27]:
test = get_fundamentals(ticker)

test

  ticker  year       revenue    net_income  total_assets
0   AAPL  2025  4.161610e+11  1.120100e+11  3.592410e+11
1   AAPL  2024  3.910350e+11  9.373600e+10  3.649800e+11
2   AAPL  2023  3.832850e+11  9.699500e+10  3.525830e+11
3   AAPL  2022  3.943280e+11  9.980300e+10  3.527550e+11
4   AAPL  2021           NaN           NaN           NaN

In [28]:
all_fundamentals = []

for ticker in companies["ticker"].dropna():
    print("Collecting:", ticker)

    result = get_fundamentals(ticker)

    if not result.empty:
        all_fundamentals.append(result)

Collecting: AAPL
Collecting: MSFT
Collecting: KO
Collecting: PEP
Collecting: JNJ
Collecting: PG
Collecting: MCD
Collecting: WMT
Collecting: XOM
Collecting: VZ

In [29]:
fundamentals = pd.concat(
    all_fundamentals,
    ignore_index=True
)

fundamentals.head()

  ticker  year       revenue    net_income  total_assets
0   AAPL  2025  4.161610e+11  1.120100e+11  3.592410e+11
1   AAPL  2024  3.910350e+11  9.373600e+10  3.649800e+11
2   AAPL  2023  3.832850e+11  9.699500e+10  3.525830e+11
3   AAPL  2022  3.943280e+11  9.980300e+10  3.527550e+11
4   AAPL  2021           NaN           NaN           NaN

In [30]:
print(
    "Companies:",
    fundamentals["ticker"].nunique()
)

print(
    "Rows:",
    len(fundamentals)
)

Companies: 10
Rows: 46

In [31]:
fundamentals.isnull().sum()

ticker          0
year            0
revenue         6
net_income      6
total_assets    6
dtype: int64

In [32]:
fundamentals.duplicated(
    subset=["ticker", "year"]
).sum()

np.int64(0)

In [33]:
fundamentals.to_csv(
    "../datasets/raw/fundamentals_real.csv",
    index=False
)

In [34]:
research_data = pd.read_csv(
    "../datasets/processed/dividend_puzzle_research_dataset.csv"
)

In [35]:
merged_data = research_data.merge(
    fundamentals,
    on=["ticker", "year"],
    how="left"
)

In [36]:
merged_data.head()

,company,ticker,year,year_end_price,dividend_per_share,dividend_yield,dividend_growth,dividend_growth_category,annual_stock_return,return_category,total_return,return_volatility,average_return,dividend_consistency,revenue,net_income,total_assets
0,Apple,AAPL,2015,26.315001,0.5075,1.93,NaN,First Year,NaN,First Year,NaN,36.16,31.01,90.91,NaN,NaN,NaN
1,Apple,AAPL,2016,28.955000,0.5575,1.93,9.85,Increased,10.03,Positive,11.96,36.16,31.01,90.91,NaN,NaN,NaN
2,Apple,AAPL,2017,42.307499,0.6150,1.45,10.31,Increased,46.11,Positive,47.56,36.16,31.01,90.91,NaN,NaN,NaN
3,Apple,AAPL,2018,39.435001,0.7050,1.79,14.63,Increased,-6.79,Negative,-5.00,36.16,31.01,90.91,NaN,NaN,NaN
4,Apple,AAPL,2019,73.412498,0.7600,1.04,7.80,Increased,86.16,Positive,87.20,36.16,31.01,90.91,NaN,NaN,NaN

In [37]:
print(
    "Research rows:",
    len(research_data)
)

print(
    "Merged rows:",
    len(merged_data)
)

Research rows: 110
Merged rows: 110

In [38]:
print(
    merged_data.columns.tolist()
)

['company', 'ticker', 'year', 'year_end_price', 'dividend_per_share', 'dividend_yield', 'dividend_growth', 'dividend_growth_category', 'annual_stock_return', 'return_category', 'total_return', 'return_volatility', 'average_return', 'dividend_consistency', 'revenue', 'net_income', 'total_assets']

In [39]:
merged_data.to_csv(
    "../datasets/processed/dividend_puzzle_fundamental_dataset.csv",
    index=False
)